"""Initial migration

Revision ID: 34bce5e124df
Revises: 
Create Date: 2026-06-15 01:46:54.272561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bce5e124df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ankieta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rok_akademicki', sa.String(length=20), nullable=False),
    sa.Column('kierunek', sa.String(length=100), nullable=False),
    sa.Column('forma_studiow', sa.String(length=50), nullable=False),
    sa.Column('semestr', sa.Integer(), nullable=False),
    sa.Column('godziny', sa.Integer(), nullable=False),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('efekt_uczenia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.CheckConstraint('nr BETWEEN 1 AND 13', name='check_efekt_nr_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nr')
    )
    op.create_table('uzytkownik',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imie', sa.String(length=100), nullable=False),
    sa.Column('nazwisko', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('haslo_hash', sa.String(length=255), nullable=False),
    sa.Column('rola', sa.String(length=50), nullable=True),
    sa.Column('microsoft_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rola IN ('student', 'zopz', 'uopz', 'administrator', 'dyrektor') OR rola IS NULL", name='check_uzytkownik_rola'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ankieta_odpowiedz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ankieta_id', sa.Integer(), nullable=False),
    sa.Column('pytanie_nr', sa.Integer(), nullable=False),
    sa.Column('odpowiedz', sa.Integer(), nullable=False),
    sa.CheckConstraint('odpowiedz BETWEEN 1 AND 5', name='check_ankieta_odpowiedz_range'),
    sa.CheckConstraint('pytanie_nr BETWEEN 1 AND 14', name='check_ankieta_pytanie_nr'),
    sa.ForeignKeyConstraint(['ankieta_id'], ['ankieta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ankieta_id', 'pytanie_nr', name='uq_ankieta_pytanie')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzytkownik_id', sa.Integer(), nullable=False),
    sa.Column('nr_albumu', sa.String(length=20), nullable=False),
    sa.Column('kierunek', sa.String(length=100), nullable=False),
    sa.Column('specjalnosc', sa.String(length=100), nullable=True),
    sa.Column('semestr', sa.Integer(), nullable=False),
    sa.Column('forma_studiow', sa.String(length=50), nullable=False),
    sa.Column('rok_akademicki', sa.String(length=20), nullable=False),
    sa.CheckConstraint("forma_studiow IN ('stacjonarne', 'niestacjonarne')", name='check_student_forma_studiow'),
    sa.CheckConstraint('semestr IN (6, 7)', name='check_student_semestr'),
    sa.ForeignKeyConstraint(['uzytkownik_id'], ['uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nr_albumu'),
    sa.UniqueConstraint('uzytkownik_id')
    )
    op.create_table('zaklad_pracy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nazwa', sa.String(length=255), nullable=False),
    sa.Column('adres', sa.String(length=255), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('zopz_imie', sa.String(length=100), nullable=False),
    sa.Column('zopz_nazwisko', sa.String(length=100), nullable=False),
    sa.Column('zopz_stanowisko', sa.String(length=100), nullable=False),
    sa.Column('zopz_wyksztalcenie', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('zopz_uzytkownik_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('Approved', 'Rejected')", name='check_zaklad_pracy_status'),
    sa.ForeignKeyConstraint(['zopz_uzytkownik_id'], ['uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('praktyka',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('zaklad_id', sa.Integer(), nullable=False),
    sa.Column('uopz_id', sa.Integer(), nullable=False),
    sa.Column('termin_od', sa.Date(), nullable=False),
    sa.Column('termin_do', sa.Date(), nullable=False),
    sa.Column('rok_akademicki', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ocena_koncowa', sa.Float(), nullable=True),
    sa.Column('ankieta_wypelniona', sa.Integer(), nullable=False),
    sa.Column('dziennik_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("dziennik_status IN ('Draft', 'Under_Review', 'Closed', 'Rejected')", name='check_praktyka_dziennik_status'),
    sa.CheckConstraint("status IN ('Draft', 'Submitted', 'Under_Review', 'Approved', 'Rejected', 'Closed')", name='check_praktyka_status'),
    sa.CheckConstraint('ankieta_wypelniona IN (0, 1)', name='check_praktyka_ankieta_flag'),
    sa.CheckConstraint('ocena_koncowa BETWEEN 2.0 AND 5.0', name='check_praktyka_ocena_range'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['uopz_id'], ['uzytkownik.id'], ),
    sa.ForeignKeyConstraint(['zaklad_id'], ['zaklad_pracy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wniosek_alternatywny',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('uzasadnienie', sa.Text(), nullable=False),
    sa.Column('opinia_komisji', sa.Text(), nullable=True),
    sa.Column('decyzja', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decyzja IN ('zgoda_pelna', 'zgoda_czesciowa', 'odmowa') OR decyzja IS NULL", name='check_wniosek_decyzja'),
    sa.CheckConstraint("status IN ('Submitted', 'Under_Review', 'Approved', 'Rejected')", name='check_wniosek_status'),
    sa.CheckConstraint("typ IN ('praca_zawodowa', 'staz', 'dzialalnosc_gospodarcza')", name='check_wniosek_typ'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dokument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=True),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('sciezka_pliku', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("typ IN ('zal_nr2a', 'zal_nr3', 'zal_nr4', 'zal_nr4b', 'zal_nr5', 'zal_nr6', 'zal_nr7', 'zal_nr8')", name='check_dokument_typ'),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyka.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egzamin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('termin', sa.DateTime(), nullable=False),
    sa.Column('ocena_ustna', sa.Float(), nullable=True),
    sa.Column('ocena_koncowa', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Draft', 'Approved', 'Rejected')", name='check_egzamin_status'),
    sa.CheckConstraint('ocena_koncowa BETWEEN 2.0 AND 5.0', name='check_egzamin_ocena_koncowa'),
    sa.CheckConstraint('ocena_ustna BETWEEN 2.0 AND 5.0', name='check_egzamin_ocena_ustna'),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyka.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonogram',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('podpis_student', sa.Integer(), nullable=False),
    sa.Column('podpis_zopz', sa.Integer(), nullable=False),
    sa.Column('podpis_uopz', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Draft', 'Submitted', 'Under_Review', 'Approved', 'Rejected')", name='check_harmonogram_status'),
    sa.CheckConstraint('podpis_student IN (0, 1)', name='check_harmonogram_podpis_student'),
    sa.CheckConstraint('podpis_uopz IN (0, 1)', name='check_harmonogram_podpis_uopz'),
    sa.CheckConstraint('podpis_zopz IN (0, 1)', name='check_harmonogram_podpis_zopz'),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyka.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('praktyka_id')
    )
    op.create_table('karta_praktyki',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('ocena_param_zopz', sa.Float(), nullable=True),
    sa.Column('ocena_opisowa_zopz', sa.Text(), nullable=True),
    sa.Column('ocena_param_uopz', sa.Float(), nullable=True),
    sa.Column('ocena_opisowa_uopz', sa.Text(), nullable=True),
    sa.Column('ocena_sprawozdania', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Draft', 'Under_Review', 'Approved', 'Closed')", name='check_karta_status'),
    sa.CheckConstraint('ocena_param_uopz BETWEEN 2.0 AND 5.0', name='check_karta_ocena_uopz'),
    sa.CheckConstraint('ocena_param_zopz BETWEEN 2.0 AND 5.0', name='check_karta_ocena_zopz'),
    sa.CheckConstraint('ocena_sprawozdania BETWEEN 2.0 AND 5.0', name='check_karta_ocena_sprawozdania'),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyka.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('praktyka_id')
    )
    op.create_table('potwierdzenie_efektow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('godziny_zrealizowane', sa.Integer(), nullable=False),
    sa.Column('opinia_uopz', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Draft', 'Submitted', 'Under_Review', 'Approved', 'Rejected')", name='check_potwierdzenie_status'),
    sa.CheckConstraint('godziny_zrealizowane > 0', name='check_potwierdzenie_godziny'),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyka.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('praktyka_id')
    )
    op.create_table('sprawozdanie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('sekcja_I', sa.Text(), nullable=False),
    sa.Column('sekcja_II', sa.Text(), nullable=False),
    sa.Column('sekcja_III', sa.Text(), nullable=False),
    sa.Column('wersja', sa.Integer(), nullable=False),
    sa.Column('ocena', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Draft', 'Submitted', 'Under_Review', 'Approved', 'Rejected')", name='check_sprawozdanie_status'),
    sa.CheckConstraint('ocena BETWEEN 2.0 AND 5.0', name='check_sprawozdanie_ocena_range'),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyka.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wpis_dziennika',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('dzien_nr', sa.Integer(), nullable=False),
    sa.Column('data_wpisu', sa.Date(), nullable=False),
    sa.Column('opis_prac', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('komentarz_zopz', sa.Text(), nullable=True),
    sa.Column('podpis_zopz', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Draft', 'Submitted', 'Approved', 'Rejected')", name='check_wpis_status'),
    sa.CheckConstraint('dzien_nr BETWEEN 1 AND 120', name='check_wpis_dzien_nr_range'),
    sa.CheckConstraint('podpis_zopz IN (0, 1)', name='check_wpis_podpis_zopz'),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyka.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('praktyka_id', 'dzien_nr', name='uq_praktyka_dzien_nr')
    )
    op.create_table('zalacznik_skan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wniosek_id', sa.Integer(), nullable=False),
    sa.Column('nazwa_pliku', sa.String(length=255), nullable=False),
    sa.Column('sciezka_pliku', sa.String(length=255), nullable=False),
    sa.Column('typ_dokumentu', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("typ_dokumentu IN ('umowa_o_prace', 'zakres_obowiazkow', 'ceidg', 'krs', 'inny')", name='check_zalacznik_typ'),
    sa.ForeignKeyConstraint(['wniosek_id'], ['wniosek_alternatywny.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonogram_dzial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('harmonogram_id', sa.Integer(), nullable=False),
    sa.Column('nazwa_dzialu', sa.String(length=255), nullable=False),
    sa.Column('planowane_dni', sa.Integer(), nullable=False),
    sa.CheckConstraint('planowane_dni > 0', name='check_harmonogram_dzial_planowane_dni'),
    sa.ForeignKeyConstraint(['harmonogram_id'], ['harmonogram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('komisja_czlonek',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('egzamin_id', sa.Integer(), nullable=False),
    sa.Column('uzytkownik_id', sa.Integer(), nullable=False),
    sa.Column('rola_w_komisji', sa.String(length=50), nullable=False),
    sa.CheckConstraint("rola_w_komisji IN ('przewodniczacy', 'czlonek')", name='check_rola_w_komisji'),
    sa.ForeignKeyConstraint(['egzamin_id'], ['egzamin.id'], ),
    sa.ForeignKeyConstraint(['uzytkownik_id'], ['uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('egzamin_id', 'uzytkownik_id', name='uq_egzamin_uzytkownik')
    )
    op.create_table('potwierdzenie_efekt_ocena',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('potwierdzenie_id', sa.Integer(), nullable=False),
    sa.Column('efekt_id', sa.Integer(), nullable=False),
    sa.Column('uzyskano', sa.Integer(), nullable=False),
    sa.CheckConstraint('uzyskano IN (0, 1)', name='check_ocena_uzyskano_flag'),
    sa.ForeignKeyConstraint(['efekt_id'], ['efekt_uczenia.id'], ),
    sa.ForeignKeyConstraint(['potwierdzenie_id'], ['potwierdzenie_efektow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('potwierdzenie_id', 'efekt_id', name='uq_potwierdzenie_efekt')
    )
    op.create_table('wpis_efekt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wpis_id', sa.Integer(), nullable=False),
    sa.Column('efekt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['efekt_id'], ['efekt_uczenia.id'], ),
    sa.ForeignKeyConstraint(['wpis_id'], ['wpis_dziennika.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wpis_id', 'efekt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wpis_efekt')
    op.drop_table('potwierdzenie_efekt_ocena')
    op.drop_table('komisja_czlonek')
    op.drop_table('harmonogram_dzial')
    op.drop_table('zalacznik_skan')
    op.drop_table('wpis_dziennika')
    op.drop_table('sprawozdanie')
    op.drop_table('potwierdzenie_efektow')
    op.drop_table('karta_praktyki')
    op.drop_table('harmonogram')
    op.drop_table('egzamin')
    op.drop_table('dokument')
    op.drop_table('wniosek_alternatywny')
    op.drop_table('praktyka')
    op.drop_table('zaklad_pracy')
    op.drop_table('student')
    op.drop_table('ankieta_odpowiedz')
    op.drop_table('uzytkownik')
    op.drop_table('efekt_uczenia')
    op.drop_table('ankieta')
    # ### end Alembic commands ###
